// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.14.0
// source: request/messages.proto

package request

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionOpenResponse_Status int32

const (
	SessionOpenResponse_OK        SessionOpenResponse_Status = 0
	SessionOpenResponse_DIAL_FAIL SessionOpenResponse_Status = 1
	SessionOpenResponse_ERROR     SessionOpenResponse_Status = 2
)

// Enum value maps for SessionOpenResponse_Status.
var (
	SessionOpenResponse_Status_name = map[int32]string{
		0: "OK",
		1: "DIAL_FAIL",
		2: "ERROR",
	}
	SessionOpenResponse_Status_value = map[string]int32{
		"OK":        0,
		"DIAL_FAIL": 1,
		"ERROR":     2,
	}
)

func (x SessionOpenResponse_Status) Enum() *SessionOpenResponse_Status {
	p := new(SessionOpenResponse_Status)
	*p = x
	return p
}

func (x SessionOpenResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionOpenResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_request_messages_proto_enumTypes[0].Descriptor()
}

func (SessionOpenResponse_Status) Type() protoreflect.EnumType {
	return &file_request_messages_proto_enumTypes[0]
}

func (x SessionOpenResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionOpenResponse_Status.Descriptor instead.
func (SessionOpenResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_request_messages_proto_rawDescGZIP(), []int{1, 0}
}

type PollResponse_Status int32

const (
	PollResponse_POLL_OK PollResponse_Status = 0
	PollResponse_NO_DATA PollResponse_Status = 1
	PollResponse_CLOSED  PollResponse_Status = 2
	PollResponse_ERROR   PollResponse_Status = 3
)

// Enum value maps for PollResponse_Status.
var (
	PollResponse_Status_name = map[int32]string{
		0: "POLL_OK",
		1: "NO_DATA",
		2: "CLOSED",
		3: "ERROR",
	}
	PollResponse_Status_value = map[string]int32{
		"POLL_OK": 0,
		"NO_DATA": 1,
		"CLOSED":  2,
		"ERROR":   3,
	}
)

func (x PollResponse_Status) Enum() *PollResponse_Status {
	p := new(PollResponse_Status)
	*p = x
	return p
}

func (x PollResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PollResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_request_messages_proto_enumTypes[1].Descriptor()
}

func (PollResponse_Status) Type() protoreflect.EnumType {
	return &file_request_messages_proto_enumTypes[1]
}

func (x PollResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PollResponse_Status.Descriptor instead.
func (PollResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_request_messages_proto_rawDescGZIP(), []int{3, 0}
}

type WriteResponse_Status int32

const (
	WriteResponse_WRITE_OK WriteResponse_Status = 0
	WriteResponse_CLOSED   WriteResponse_Status = 1
	WriteResponse_ERROR    WriteResponse_Status = 2
)

// Enum value maps for WriteResponse_Status.
var (
	WriteResponse_Status_name = map[int32]string{
		0: "WRITE_OK",
		1: "CLOSED",
		2: "ERROR",
	}
	WriteResponse_Status_value = map[string]int32{
		"WRITE_OK": 0,
		"CLOSED":   1,
		"ERROR":    2,
	}
)

func (x WriteResponse_Status) Enum() *WriteResponse_Status {
	p := new(WriteResponse_Status)
	*p = x
	return p
}

func (x WriteResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WriteResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_request_messages_proto_enumTypes[2].Descriptor()
}

func (WriteResponse_Status) Type() protoreflect.EnumType {
	return &file_request_messages_proto_enumTypes[2]
}

func (x WriteResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WriteResponse_Status.Descriptor instead.
func (WriteResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_request_messages_proto_rawDescGZIP(), []int{5, 0}
}

type SessionOpenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DestAddr string `protobuf:"bytes,1,opt,name=destAddr,proto3" json:"destAddr,omitempty"`
}

func (x *SessionOpenRequest) Reset() {
	*x = SessionOpenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_request_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionOpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionOpenRequest) ProtoMessage() {}

func (x *SessionOpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_request_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionOpenRequest.ProtoReflect.Descriptor instead.
func (*SessionOpenRequest) Descriptor() ([]byte, []int) {
	return file_request_messages_proto_rawDescGZIP(), []int{0}
}

func (x *SessionOpenRequest) GetDestAddr() string {
	if x != nil {
		return x.DestAddr
	}
	return ""
}

type SessionOpenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status SessionOpenResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=SessionOpenResponse_Status" json:"status,omitempty"`
	Id     uint64                     `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *SessionOpenResponse) Reset() {
	*x = SessionOpenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_request_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionOpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionOpenResponse) ProtoMessage() {}

func (x *SessionOpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_request_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionOpenResponse.ProtoReflect.Descriptor instead.
func (*SessionOpenResponse) Descriptor() ([]byte, []int) {
	return file_request_messages_proto_rawDescGZIP(), []int{1}
}

func (x *SessionOpenResponse) GetStatus() SessionOpenResponse_Status {
	if x != nil {
		return x.Status
	}
	return SessionOpenResponse_OK
}

func (x *SessionOpenResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PollRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PollRequest) Reset() {
	*x = PollRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_request_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollRequest) ProtoMessage() {}

func (x *PollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_request_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollRequest.ProtoReflect.Descriptor instead.
func (*PollRequest) Descriptor() ([]byte, []int) {
	return file_request_messages_proto_rawDescGZIP(), []int{2}
}

func (x *PollRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PollResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status PollResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=PollResponse_Status" json:"status,omitempty"`
	Data   []byte              `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PollResponse) Reset() {
	*x = PollResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_request_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollResponse) ProtoMessage() {}

func (x *PollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_request_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollResponse.ProtoReflect.Descriptor instead.
func (*PollResponse) Descriptor() ([]byte, []int) {
	return file_request_messages_proto_rawDescGZIP(), []int{3}
}

func (x *PollResponse) GetStatus() PollResponse_Status {
	if x != nil {
		return x.Status
	}
	return PollResponse_POLL_OK
}

func (x *PollResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_request_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_request_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_request_messages_proto_rawDescGZIP(), []int{4}
}

func (x *WriteRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WriteRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status WriteResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=WriteResponse_Status" json:"status,omitempty"`
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_request_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_request_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_request_messages_proto_rawDescGZIP(), []int{5}
}

func (x *WriteResponse) GetStatus() WriteResponse_Status {
	if x != nil {
		return x.Status
	}
	return WriteResponse_WRITE_OK
}

var File_request_messages_proto protoreflect.FileDescriptor

var file_request_messages_proto_rawDesc = []byte{
	0x0a, 0x16, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x30, 0x0a, 0x12, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x4f, 0x70, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x64, 0x65, 0x73, 0x74, 0x41, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x64, 0x65, 0x73, 0x74, 0x41, 0x64, 0x64, 0x72, 0x22, 0x86, 0x01, 0x0a, 0x13, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4f, 0x70, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4f, 0x70, 0x65, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2a, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x44, 0x49, 0x41,
	0x4c, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x10, 0x02, 0x22, 0x1d, 0x0a, 0x0b, 0x50, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x8b, 0x01, 0x0a, 0x0c, 0x50, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x50, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x39, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x0b, 0x0a, 0x07, 0x50, 0x4f, 0x4c, 0x4c, 0x5f, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07,
	0x4e, 0x4f, 0x5f, 0x44, 0x41, 0x54, 0x41, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x4c, 0x4f,
	0x53, 0x45, 0x44, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x03,
	0x22, 0x32, 0x0a, 0x0c, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x6d, 0x0a, 0x0d, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0x2d, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0c,
	0x0a, 0x08, 0x57, 0x52, 0x49, 0x54, 0x45, 0x5f, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x43, 0x4c, 0x4f, 0x53, 0x45, 0x44, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x10, 0x02, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2e, 0x2f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_request_messages_proto_rawDescOnce sync.Once
	file_request_messages_proto_rawDescData = file_request_messages_proto_rawDesc
)

func file_request_messages_proto_rawDescGZIP() []byte {
	file_request_messages_proto_rawDescOnce.Do(func() {
		file_request_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_request_messages_proto_rawDescData)
	})
	return file_request_messages_proto_rawDescData
}

var file_request_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_request_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_request_messages_proto_goTypes = []interface{}{
	(SessionOpenResponse_Status)(0), // 0: SessionOpenResponse.Status
	(PollResponse_Status)(0),        // 1: PollResponse.Status
	(WriteResponse_Status)(0),       // 2: WriteResponse.Status
	(*SessionOpenRequest)(nil),      // 3: SessionOpenRequest
	(*SessionOpenResponse)(nil),     // 4: SessionOpenResponse
	(*PollRequest)(nil),             // 5: PollRequest
	(*PollResponse)(nil),            // 6: PollResponse
	(*WriteRequest)(nil),            // 7: WriteRequest
	(*WriteResponse)(nil),           // 8: WriteResponse
}
var file_request_messages_proto_depIdxs = []int32{
	0, // 0: SessionOpenResponse.status:type_name -> SessionOpenResponse.Status
	1, // 1: PollResponse.status:type_name -> PollResponse.Status
	2, // 2: WriteResponse.status:type_name -> WriteResponse.Status
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_request_messages_proto_init() }
func file_request_messages_proto_init() {
	if File_request_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_request_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionOpenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_request_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionOpenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_request_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PollRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_request_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PollResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_request_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_request_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_request_messages_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_messages_proto_goTypes,
		DependencyIndexes: file_request_messages_proto_depIdxs,
		EnumInfos:         file_request_messages_proto_enumTypes,
		MessageInfos:      file_request_messages_proto_msgTypes,
	}.Build()
	File_request_messages_proto = out.File
	file_request_messages_proto_rawDesc = nil
	file_request_messages_proto_goTypes = nil
	file_request_messages_proto_depIdxs = nil
}
